GRANT USAGE ON SCHEMA webconference TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA webconference TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA webconference TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA webconference TO "apps";